export const destinationsData = [
  {
    id: "machu-picchu",
    title: "Machu Picchu, Cusco",
    region: "Sierra",
    badgeColor: "info",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/14/db/41/caption.jpg?w=1200&h=-1&s=1",
    alt: "Santuario Histórico de Machu Picchu con ruinas incas y montañas",
    description: "Ciudadela inca declarada Patrimonio de la Humanidad por la UNESCO y una de las Siete Maravillas del Mundo Moderno. Impresionante ejemplo de arquitectura inca en perfecta armonía con la naturaleza.",
    activities: ["Senderismo", "Observación de fauna andina", "Visitas arqueológicas guiadas"],
    bestTime: "Mayo a octubre (temporada seca)",
    difficulty: "Moderado",
    duration: "1-2 días",
    communities: "Visita a comunidades quechuas que mantienen tradiciones ancestrales y ofrecen servicios turísticos sostenibles.",
    category: ["sierra", "senderismo", "arqueologia"]
  },
  {
    id: "lago-titicaca",
    title: "Lago Titicaca, Puno",
    region: "Sierra",
    badgeColor: "success",
    image: "https://www.peru.travel/Contenido/Atractivo/Imagen/es/32/1.1/Principal/comunidad-andina-en-el-lago-titicaca.jpg",
    alt: "Lago Titicaca con islas flotantes de los Uros",
    description: "El lago navegable más alto del mundo, hogar de comunidades quechuas y aymaras que mantienen tradiciones ancestrales como las islas flotantes de los Uros.",
    activities: ["Navegación por el lago", "Visita a islas tradicionales", "Talleres de artesanía local"],
    bestTime: "Mayo a octubre",
    difficulty: "Bajo a moderado",
    duration: "2-3 días",
    communities: "Experiencia de turismo comunitario gestionado por comunidades aymaras y quechuas que mantienen tradiciones milenarias.",
    category: ["sierra", "acuaticas", "cultural"]
  },
  {
    id: "tambopata",
    title: "Reserva de Tambopata, Madre de Dios",
    region: "Selva",
    badgeColor: "success",
    image: "https://cloudfront-us-east-1.images.arcpublishing.com/infobae/LBMC6LM3ENAJLJ7DW7V5M5X3ZQ.png",
    alt: "Reserva Nacional de Tambopata con río y selva amazónica",
    description: "Una de las regiones con mayor biodiversidad de Perú, hogar de comunidades nativas que preservan la selva amazónica y una increíble variedad de flora y fauna.",
    activities: ["Observación de fauna amazónica", "Navegación por ríos", "Caminatas en selva tropical"],
    bestTime: "Mayo a octubre (temporada seca)",
    difficulty: "Moderado",
    duration: "3-5 días",
    communities: "Visita a comunidades nativas amazónicas que mantienen tradiciones ancestrales y protegen la selva.",
    category: ["selva", "observacion", "senderismo"]
  },
  {
    id: "colca",
    title: "Cañón del Colca, Arequipa",
    region: "Andes",
    badgeColor: "warning",
    image: "https://www.peru.travel/Contenido/Experiencia/Imagen/es/67/1.1/Visita%20al%20canon%20del%20colca.jpg",
    alt: "Cañón del Colca con cóndores volando sobre el abismo",
    description: "Uno de los cañones más profundos del mundo y hogar del majestuoso cóndor andino. Ofrece impresionantes paisajes y rica cultura local.",
    activities: ["Observación de cóndores", "Trekking por el cañón", "Baños termales naturales"],
    bestTime: "Mayo a noviembre",
    difficulty: "Moderado a alto",
    duration: "2-3 días",
    communities: "Comunidades collaguas y cabanas que mantienen tradiciones ancestrales y participan en el turismo sostenible.",
    category: ["andes", "senderismo", "observacion"]
  },
  {
    id: "paracas",
    title: "Reserva Nacional de Paracas, Ica",
    region: "Costa",
    badgeColor: "info",
    image: "https://www.machupicchuperutours.com/wp-content/uploads/Reserva-Nacional-de-Paracas-3.jpg",
    alt: "Reserva Nacional de Paracas con formaciones rocosas y mar azul",
    description: "Reserva marina y terrestre que alberga una gran biodiversidad, impresionantes acantilados, playas vírgenes y las enigmáticas Islas Ballestas.",
    activities: ["Observación de fauna marina", "Paseo en bote a las Islas Ballestas", "Recorrido por la reserva terrestre"],
    bestTime: "Todo el año (preferible diciembre a marzo)",
    difficulty: "Bajo",
    duration: "1-2 días",
    communities: "Pescadores artesanales que ofrecen tours y comparten conocimientos sobre el ecosistema marino.",
    category: ["costa", "observacion", "acuaticas"]
  },
  {
    id: "huascaran",
    title: "Parque Nacional Huascarán, Ancash",
    region: "Andes",
    badgeColor: "danger",
    image: "https://i0.wp.com/www.actualidadambiental.pe/wp-content/uploads/2019/08/huascaran-andina.jpg?resize=800%2C533",
    alt: "Parque Nacional Huascarán con nevados y lagunas glaciares",
    description: "Hogar de la montaña más alta de Perú y de impresionantes glaciares, lagunas turquesas y flora y fauna andina. Declarado Patrimonio Natural de la Humanidad por la UNESCO.",
    activities: ["Trekking por la Cordillera Blanca", "Escalada en hielo y roca", "Fotografía de paisajes andinos"],
    bestTime: "Mayo a septiembre (temporada seca)",
    difficulty: "Moderado a alto",
    duration: "3-7 días",
    communities: "Comunidades quechuas que mantienen tradiciones ancestrales y ofrecen servicios de guía y hospedaje.",
    category: ["andes", "senderismo", "observacion"]
  }
];
